server:
  port: 3015

spring:
  application:
    name: back-cvs
    directorio-cv: uploads/cv

  security:
    jwt:
      secret-key: VGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkgZm9yIEpXVFMhIQ== # 游댮 Reemplazar en producci칩n con una variable de entorno
      expiration: 3600000 # 1 hora equivale la secion del usuario
      refresh-token:
        expiration: 604800000 # 7 d칤as en milisegundos

    user:
      name: renzord # usuario-
      password: 12345

  sql:
    init:
      platform: postgres

  datasource:
    url: jdbc:postgresql://localhost:7075/civia-data # Nombre de la base-de-datos
    username: postgres # user create use modificar-contrase침a entorno a producion
    password: root # modificar contrase침a en enetorno de producion
  jpa:
    show-sql: true  # Cambia a 'false' en producci칩n
    generate-ddl: true
    database: POSTGRESQL
    properties:
      hibernate:
        format-sql: true
        ddl-auto: update # Considera cambiar a 'none' o 'validate', 'update', 'create', 'create-drop' en producci칩n

  # Subida de archivos
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  ## falta a{adir ruta para guarda rlos archivos

api:
  prefix: /api/v2